name = "peter-property"
compatibility_date = "2025-01-10"
pages_build_output_dir = "out"

# Cloudflare Pages configuration for Next.js static export
[site]
bucket = "./out"

# Custom routes for better SEO
[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

# Ensure all routes are served properly
[[redirects]]
from = "/*"
to = "/404.html"
status = 404
